#!/usr/bin/env python3
"""Single source of truth for every engine integration artifact.

Run after changing guidance.py, the canonical skill, the example agent, the
project version, or INSTALL_PHASE:

    uv run python scripts/gen_integrations.py

Outputs: everything under integrations/, examples/prompts/, both .mcp.json
files, server.json (MCP registry manifest), and the marked install region
inside README.md (one-click buttons + per-client matrix). NEVER hand-edit
the generated files; `tests/unit/test_guidance.py` byte-pins all of them to
this generator.

Flip-day note: switching distribution from the git checkout to PyPI is ONE
change — set INSTALL_PHASE = "pypi" and re-run. That also turns on the
one-click install buttons in README.md (their deep links only work once the
PyPI package exists).
"""

from __future__ import annotations

import base64
import json
import sys
import tomllib
import urllib.parse
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from talkthrough_mcp import guidance  # noqa: E402

# --- the one flip-day switch -------------------------------------------------

INSTALL_PHASE = "pypi"  # "git" (private/pre-PyPI) | "pypi"

# Generated configs are batteries-included: they carry the [diarization]
# extra so a user who installed via any one-click button / plugin / snippet
# can ask "who said what" without reinstalling (v0.2.0 decision). The
# PACKAGE default stays lean — `uvx talkthrough-mcp` remains the documented
# minimal install — and diarization itself is still off per call.
_PYPI_SPEC = "talkthrough-mcp[diarization]"
_GIT_SPEC = "talkthrough-mcp[diarization] @ git+https://github.com/korovin-aa97/talkthrough-mcp"
_UVX_ARGS = {
    "git": ["--from", _GIT_SPEC, "talkthrough-mcp"],
    "pypi": [_PYPI_SPEC],
}
UVX_ARGS: list[str] = _UVX_ARGS[INSTALL_PHASE]


def _shell_quoted(arg: str) -> str:
    """Quote args for shell one-liners (zsh globs bare [] patterns)."""
    return f'"{arg}"' if any(ch in arg for ch in "[] @") else arg


UVX_CMDLINE = "uvx " + " ".join(_shell_quoted(arg) for arg in UVX_ARGS)

PROJECT_VERSION: str = tomllib.loads((REPO / "pyproject.toml").read_text(encoding="utf-8"))[
    "project"
]["version"]

ENV_DOC = (
    "Optional env vars: TALKTHROUGH_WHISPER_MODEL (default `small`; use "
    "`large-v3-turbo` for non-English narration — agents can also pass "
    "`model=` per call), TALKTHROUGH_OCR (`off` to disable), "
    "TALKTHROUGH_OCR_LANG (on-screen-text script, e.g. `ru`, `ja`, `ko`), "
    "TALKTHROUGH_HOME (job store root, default `~/.talkthrough`). "
    "Speaker diarization is included but off per call — agents pass "
    "`diarize=true` (plus `num_speakers` when known); the minimal server "
    "without the diarization engine is `uvx talkthrough-mcp`."
)

VERIFY_DOC = (
    "Verify: the client should list 7 tools (process_media, get_transcript, get_frames, "
    "get_moment, search, extract_frame, list_jobs). A `list_jobs` call returning an empty "
    "list is a healthy first run."
)

README_BEGIN = "<!-- gen:install — generated by scripts/gen_integrations.py; do not hand-edit -->"
README_END = "<!-- /gen:install -->"

# --- helpers ------------------------------------------------------------------


def _jsonc(payload: dict) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _engine_readme(
    title: str,
    config_path: str,
    snippet_lang: str,
    snippet: str,
    extra: str = "",
    docs_url: str | None = None,
) -> str:
    parts = [
        f"# {title}\n",
        "\nServer command (stdio): `" + UVX_CMDLINE + "`\n",
        f"\nConfig: `{config_path}`\n",
        f"\n```{snippet_lang}\n{snippet}```\n",
    ]
    if extra:
        parts.append("\n" + extra.rstrip() + "\n")
    parts.append("\n" + ENV_DOC + "\n")
    parts.append("\n" + VERIFY_DOC + "\n")
    if docs_url:
        parts.append(f"\nEngine docs: <{docs_url}>\n")
    parts.append(
        "\nAgent-followable install steps for any client: [`llms-install.md`](../../llms-install.md).\n"
    )
    return "".join(parts)


def _mcp_servers_json(command: str, args: list[str]) -> str:
    return _jsonc({"mcpServers": {"talkthrough": {"command": command, "args": args}}})


# --- engine catalog (drives both integrations/<engine>/ docs and the README matrix)


ENGINE_SPECS: list[dict[str, str]] = [
    {
        "dir": "codex",
        "title": "OpenAI Codex CLI",
        "config_path": "~/.codex/config.toml (or project-scoped .codex/config.toml in trusted projects)",
        "lang": "toml",
        "snippet": (
            "[mcp_servers.talkthrough]\n"
            'command = "uvx"\n'
            f"args = {json.dumps(UVX_ARGS)}\n"
        ),
        "extra": (
            "Skills: this repo ships the talkthrough skill at `.agents/skills/talkthrough/` — "
            "Codex discovers it automatically inside a checkout; for global use copy it to "
            "`~/.agents/skills/` and invoke with `$talkthrough`."
        ),
        "docs_url": "https://developers.openai.com/codex/mcp",
    },
    {
        "dir": "openclaw",
        "title": "OpenClaw",
        "config_path": "~/.openclaw/openclaw.json",
        "lang": "json",
        "snippet": _jsonc(
            {"mcp": {"servers": {"talkthrough": {"command": "uvx", "args": UVX_ARGS}}}}
        ),
        "extra": (
            "Or via CLI:\n\n```bash\nopenclaw mcp add talkthrough --command uvx "
            + " ".join(f"--arg {arg}" for arg in UVX_ARGS)
            + "\n```\n\nClawHub: a publish-ready skill wrapper lives in "
            "[`clawhub/`](clawhub/) (submit after the repo is public)."
        ),
        "docs_url": "https://docs.openclaw.ai/cli/mcp",
    },
    {
        "dir": "gemini-cli",
        "title": "Gemini CLI",
        "config_path": "~/.gemini/settings.json",
        "lang": "json",
        "snippet": _mcp_servers_json("uvx", UVX_ARGS),
        "docs_url": "https://google-gemini.github.io/gemini-cli/docs/tools/mcp-server.html",
    },
    {
        "dir": "cursor",
        "title": "Cursor",
        "config_path": "~/.cursor/mcp.json (or project .cursor/mcp.json)",
        "lang": "json",
        "snippet": _mcp_servers_json("uvx", UVX_ARGS),
        "docs_url": "https://cursor.com/docs/context/mcp",
    },
    {
        "dir": "cline",
        "title": "Cline / Roo Code",
        "config_path": "cline_mcp_settings.json (via MCP Servers UI)",
        "lang": "json",
        "snippet": _mcp_servers_json("uvx", UVX_ARGS),
        "extra": (
            "Fastest path: ask Cline to install it — point it at "
            "[`llms-install.md`](../../llms-install.md)."
        ),
        "docs_url": "https://docs.cline.bot/mcp/configuring-mcp-servers",
    },
    {
        "dir": "opencode",
        "title": "OpenCode",
        "config_path": "opencode.json (project) or ~/.config/opencode/opencode.json",
        "lang": "json",
        "snippet": _jsonc(
            {
                "mcp": {
                    "talkthrough": {
                        "type": "local",
                        "command": ["uvx", *UVX_ARGS],
                        "enabled": True,
                    }
                }
            }
        ),
        "docs_url": "https://opencode.ai/docs/mcp-servers",
    },
    {
        "dir": "goose",
        "title": "Goose",
        "config_path": "~/.config/goose/config.yaml",
        "lang": "yaml",
        "snippet": (
            "extensions:\n"
            "  talkthrough:\n"
            "    enabled: true\n"
            "    type: stdio\n"
            "    cmd: uvx\n"
            f"    args: {json.dumps(UVX_ARGS)}\n"
        ),
        "docs_url": "https://block.github.io/goose/docs/getting-started/using-extensions",
    },
    {
        "dir": "copilot-cli",
        "title": "GitHub Copilot CLI",
        "config_path": "~/.copilot/mcp-config.json",
        "lang": "json",
        "snippet": _mcp_servers_json("uvx", UVX_ARGS),
        "docs_url": "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/use-copilot-cli",
    },
    {
        "dir": "windsurf",
        "title": "Windsurf",
        "config_path": "~/.codeium/windsurf/mcp_config.json",
        "lang": "json",
        "snippet": _mcp_servers_json("uvx", UVX_ARGS),
        "docs_url": "https://docs.windsurf.com/windsurf/cascade/mcp",
    },
    {
        "dir": "zed",
        "title": "Zed",
        "config_path": "settings.json (Zed)",
        "lang": "json",
        "snippet": _jsonc(
            {
                "context_servers": {
                    "talkthrough": {
                        "source": "custom",
                        "command": {"path": "uvx", "args": UVX_ARGS},
                    }
                }
            }
        ),
        "docs_url": "https://zed.dev/docs/ai/mcp",
    },
]

# Claude Desktop appears only in the README matrix: integrations/claude-desktop/
# stays the one hand-maintained folder (the .mcpb manifest draft).
_CLAUDE_DESKTOP_ENTRY: dict[str, str] = {
    "dir": "claude-desktop",
    "title": "Claude Desktop",
    "config_path": "claude_desktop_config.json",
    "lang": "json",
    "snippet": _mcp_servers_json("uvx", UVX_ARGS),
}

_MATRIX_ORDER = [
    "cursor",
    "codex",
    "gemini-cli",
    "cline",
    "openclaw",
    "opencode",
    "goose",
    "copilot-cli",
    "windsurf",
    "zed",
]
_SPEC_BY_DIR = {spec["dir"]: spec for spec in ENGINE_SPECS}
MATRIX_ENTRIES: list[dict[str, str]] = [_CLAUDE_DESKTOP_ENTRY] + [
    _SPEC_BY_DIR[name] for name in _MATRIX_ORDER
]


# --- README install region ------------------------------------------------------


def _install_buttons(uvx_args: list[str]) -> str:
    """One-click deep-link badges (formats verified against top MCP repos 2026-07)."""
    config = json.dumps({"command": "uvx", "args": uvx_args}, separators=(",", ":"))
    stdio_config = json.dumps(
        {"command": "uvx", "args": uvx_args, "type": "stdio"}, separators=(",", ":")
    )
    b64 = urllib.parse.quote(base64.b64encode(config.encode()).decode(), safe="")
    url = urllib.parse.quote(config, safe="")
    url_stdio = urllib.parse.quote(stdio_config, safe="")
    # No Goose button: block.github.io/goose/extension?… 404s ecosystem-wide
    # since their site restructure (checked 2026-07-11; even playwright-mcp's
    # button is dead). Goose users get the YAML config from the matrix below.
    buttons = [
        f"[![Install in Cursor](https://cursor.com/deeplink/mcp-install-dark.svg)](https://cursor.com/en/install-mcp?name=talkthrough&config={b64})",
        f"[![Install in VS Code](https://img.shields.io/badge/VS_Code-Install_Server-0098FF?style=flat-square&logo=visualstudiocode&logoColor=white)](https://vscode.dev/redirect/mcp/install?name=talkthrough&config={url_stdio})",
        f"[![Install in VS Code Insiders](https://img.shields.io/badge/VS_Code_Insiders-Install_Server-24bfa5?style=flat-square&logo=visualstudiocode&logoColor=white)](https://insiders.vscode.dev/redirect/mcp/install?name=talkthrough&config={url_stdio}&quality=insiders)",
        f"[![Add to LM Studio](https://files.lmstudio.ai/deeplink/mcp-install-light.svg)](https://lmstudio.ai/install-mcp?name=talkthrough&config={b64})",
        f"[![Add to Kiro](https://kiro.dev/images/add-to-kiro.svg)](https://kiro.dev/launch/mcp/add?name=talkthrough&config={url})",
    ]
    return "\n".join(buttons) + "\n"


def _details_block(entry: dict[str, str]) -> str:
    return (
        "<details>\n"
        f"<summary><b>{entry['title']}</b></summary>\n\n"
        f"`{entry['config_path']}`:\n\n"
        f"```{entry['lang']}\n{entry['snippet']}```\n\n"
        f"More: [`integrations/{entry['dir']}/`](integrations/{entry['dir']}/)\n\n"
        "</details>\n"
    )


def readme_install_region() -> str:
    parts: list[str] = []
    if INSTALL_PHASE == "pypi":
        parts.append(_install_buttons(UVX_ARGS))
    if INSTALL_PHASE == "git":
        claude_add = (
            "# private-phase install (needs git access to the repo):\n"
            f"claude mcp add -s user talkthrough -- {UVX_CMDLINE}"
        )
    else:
        claude_add = f"claude mcp add -s user talkthrough -- {UVX_CMDLINE}"
    parts.append(
        "### Claude Code\n"
        "\n"
        "Two install paths — **pick one**, not both (the plugin already includes\n"
        "the server; installing both would register it twice):\n"
        "\n"
        "**Server only** — the 7 tools + 5 prompts, and nothing else on your\n"
        "system. Choose this for a minimal setup, or when you manage MCP servers\n"
        "yourself across several clients:\n"
        "\n"
        f"```bash\n{claude_add}\n```\n"
        "\n"
        "**Full plugin** — the same server, plus native slash commands\n"
        "(`/talkthrough:triage-recording`, …) that handle the ceremony for you,\n"
        "a ready-made triage subagent, and an agent skill that teaches Claude the\n"
        "workflow. Choose this for the best out-of-the-box experience:\n"
        "\n"
        "```\n"
        "/plugin marketplace add korovin-aa97/talkthrough-mcp\n"
        "/plugin install talkthrough@talkthrough\n"
        "```\n"
    )
    parts.append("### Every other MCP client\n")
    parts.extend(_details_block(entry) for entry in MATRIX_ENTRIES)
    parts.append(
        f"Any other MCP stdio client uses the same server command: `{UVX_CMDLINE}`.\n"
        "Per-engine folders with exactly these snippets plus verification steps live\n"
        "in [`integrations/`](integrations/); agents can self-install via\n"
        "[`llms-install.md`](llms-install.md).\n"
    )
    return "\n".join(parts)


def spliced_readme(text: str) -> str:
    """Return README text with the marked install region regenerated."""
    if README_BEGIN not in text or README_END not in text:
        raise SystemExit("README.md is missing the gen:install markers")
    head, _, rest = text.partition(README_BEGIN)
    _, _, tail = rest.partition(README_END)
    return head + README_BEGIN + "\n\n" + readme_install_region() + "\n" + README_END + tail


# --- artifact builders ---------------------------------------------------------


def build_claude_commands() -> dict[str, str]:
    preamble = (
        "If no job_id was passed as an argument: call list_jobs() to find the "
        "right recording, or process_media(path) if the user gave a file path — "
        "then follow the workflow below with that job_id.\n\n"
    )
    artifacts: dict[str, str] = {}
    for name in guidance.PROMPT_NAMES:
        body = guidance.render_prompt(name, "$ARGUMENTS")
        desc = guidance.PROMPT_DESCRIPTIONS[name].replace('"', "'")
        artifacts[f"integrations/claude-code/commands/{name}.md"] = (
            f'---\ndescription: "{desc}"\n---\n\n{preamble}{body}'
        )
    return artifacts


def build_example_prompts() -> dict[str, str]:
    return {
        f"examples/prompts/{name}.md": guidance.render_prompt(name, "<job_id>")
        for name in guidance.PROMPT_NAMES
    }


def build_skill_mirrors() -> dict[str, str]:
    canonical = (REPO / ".agents" / "skills" / "talkthrough" / "SKILL.md").read_text(
        encoding="utf-8"
    )
    return {"integrations/claude-code/skills/talkthrough/SKILL.md": canonical}


def build_agent_mirrors() -> dict[str, str]:
    canonical = (REPO / "examples" / "agents" / "feedback-triage.md").read_text(encoding="utf-8")
    return {"integrations/claude-code/agents/feedback-triage.md": canonical}


def build_mcp_configs() -> dict[str, str]:
    return {
        # Plugin config: distribution form (uvx).
        "integrations/claude-code/.mcp.json": _jsonc(
            {"mcpServers": {"talkthrough": {"command": "uvx", "args": UVX_ARGS}}}
        ),
        # Checkout config: contributors get the LOCAL server when opening this repo.
        ".mcp.json": _jsonc(
            {
                "mcpServers": {
                    "talkthrough-dev": {
                        "command": "uv",
                        "args": [
                            "run", "--extra", "diarization", "--directory", ".",
                            "talkthrough-mcp",
                        ],
                    }
                }
            }
        ),
    }


def build_engine_docs() -> dict[str, str]:
    return {
        f"integrations/{spec['dir']}/README.md": _engine_readme(
            spec["title"],
            spec["config_path"],
            spec["lang"],
            spec["snippet"],
            extra=spec.get("extra", ""),
            docs_url=spec["docs_url"],
        )
        for spec in ENGINE_SPECS
    }


def build_plugin_manifests() -> dict[str, str]:
    """Claude Code plugin + marketplace + Claude Desktop (.mcpb) manifests.

    Versions track pyproject so releases can't leave them behind (the 0.1.0→
    0.1.3 launch weekend did exactly that before these were generated)."""
    plugin = {
        "name": "talkthrough",
        "description": (
            "Turn narrated screen recordings into filed bugs, specs, backlogs and "
            "meeting actions. Bundles the talkthrough MCP server, five workflow "
            "commands, a triage agent, and an agent skill."
        ),
        "version": PROJECT_VERSION,
        "author": {"name": "korovin-aa97", "url": "https://github.com/korovin-aa97"},
        "homepage": "https://github.com/korovin-aa97/talkthrough-mcp",
        "repository": "https://github.com/korovin-aa97/talkthrough-mcp",
        "license": "MIT",
        "keywords": [
            "mcp", "screen-recording", "transcription", "whisper", "ocr",
            "feedback", "triage",
        ],
    }
    marketplace = {
        "name": "talkthrough",
        "owner": {"name": "korovin-aa97", "url": "https://github.com/korovin-aa97"},
        "metadata": {
            "description": (
                "Marketplace for the talkthrough plugin: narrated screen recordings "
                "in, agent-ready evidence out."
            ),
            "version": PROJECT_VERSION,
        },
        "plugins": [
            {
                "name": "talkthrough",
                "source": "./integrations/claude-code",
                "description": (
                    "Turn narrated screen recordings into filed bugs, specs, backlogs "
                    "and meeting actions — local Whisper + keyframes + OCR + "
                    "wall-clock via the talkthrough MCP server."
                ),
            }
        ],
    }
    mcpb = {
        "manifest_version": "0.2",
        "name": "talkthrough",
        "display_name": "Talkthrough — narrated recordings for your agent",
        "version": PROJECT_VERSION,
        "description": (
            "Turn narrated screen recordings into structured evidence: local Whisper "
            "transcript, scene keyframes, OCR, wall-clock anchoring. Record, talk — "
            "Claude files the bugs."
        ),
        "author": {"name": "korovin-aa97", "url": "https://github.com/korovin-aa97"},
        "license": "MIT",
        "homepage": "https://github.com/korovin-aa97/talkthrough-mcp",
        "server": {
            "type": "binary",
            "entry_point": "uvx",
            "mcp_config": {
                "command": "uvx",
                "args": UVX_ARGS,
                "env": {"TALKTHROUGH_WHISPER_MODEL": "${user_config.whisper_model}"},
            },
        },
        "user_config": {
            "whisper_model": {
                "type": "string",
                "title": "Whisper model",
                "description": (
                    "tiny | base | small | medium | large-v3 | large-v3-turbo "
                    "(default small; large-v3-turbo recommended for non-English narration)"
                ),
                "default": "small",
                "required": False,
            }
        },
        "compatibility": {"platforms": ["darwin", "linux"]},
    }
    return {
        "integrations/claude-code/.claude-plugin/plugin.json": _jsonc(plugin),
        ".claude-plugin/marketplace.json": _jsonc(marketplace),
        "integrations/claude-desktop/manifest.json": _jsonc(mcpb),
    }


def build_registry_manifest() -> dict[str, str]:
    manifest = {
        "$schema": "https://static.modelcontextprotocol.io/schemas/2025-09-29/server.schema.json",
        "name": "io.github.korovin-aa97/talkthrough-mcp",
        # Registry hard limit: <= 100 chars (enforced server-side, checked 2026-07-11).
        "description": (
            "Narrated screen recordings into agent-ready data: "
            "local transcript, keyframes, OCR, wall-clock."
        ),
        "repository": {
            "url": "https://github.com/korovin-aa97/talkthrough-mcp",
            "source": "github",
        },
        "version": PROJECT_VERSION,
        "packages": [
            {
                "registryType": "pypi",
                "registryBaseUrl": "https://pypi.org",
                "identifier": "talkthrough-mcp",
                "version": PROJECT_VERSION,
                "runtimeHint": "uvx",
                "transport": {"type": "stdio"},
                "environmentVariables": [
                    {
                        "name": "TALKTHROUGH_WHISPER_MODEL",
                        "description": (
                            "Whisper model (tiny|base|small|medium|large-v3|large-v3-turbo). "
                            "Default: small. Use large-v3-turbo for non-English narration; "
                            "the process_media `model` param overrides per call."
                        ),
                        "isRequired": False,
                        "isSecret": False,
                    },
                    {
                        "name": "TALKTHROUGH_OCR",
                        "description": "Set to 'off' to disable OCR of keyframes. Default: on.",
                        "isRequired": False,
                        "isSecret": False,
                    },
                    {
                        "name": "TALKTHROUGH_OCR_LANG",
                        "description": (
                            "Recognition script for on-screen text: a language code (ru, ja, "
                            "ko, ar, hi, ...) or a RapidOCR pack name (eslav, cyrillic, ...). "
                            "Default: Latin+Chinese."
                        ),
                        "isRequired": False,
                        "isSecret": False,
                    },
                    {
                        "name": "TALKTHROUGH_HOME",
                        "description": "Job store root. Default: ~/.talkthrough",
                        "isRequired": False,
                        "isSecret": False,
                    },
                ],
            }
        ],
    }
    return {"server.json": _jsonc(manifest)}


def build_clawhub_skill() -> dict[str, str]:
    content = f"""---
name: talkthrough
description: Analyze narrated screen recordings and audio files — timestamped transcript, scene keyframes, OCR text, and wall-clock anchoring via the local talkthrough MCP server. Use when the user shares a recording or asks to triage feedback, extract meeting actions, or correlate a recording with logs.
---

# talkthrough for OpenClaw

This skill wires the talkthrough MCP server into OpenClaw and teaches the
workflow. Everything runs locally: recordings never leave the machine.

## Setup (once)

Add the MCP server:

```bash
openclaw mcp add talkthrough --command uvx {" ".join(f"--arg {arg}" for arg in UVX_ARGS)}
```

Requires `uv` (https://astral.sh/uv). First processing downloads a whisper
model once (~460 MB for the default `small`).

## Workflow

1. `process_media(path)` — idempotent by content hash; returns a compact
   summary with job_id (re-calls on the same file are instant).
2. `get_transcript(job_id)` / `search(job_id, "<word>")` — orient; search
   covers speech AND on-screen OCR text.
3. `get_moment(job_id, t0-2000, t1+2000)` — evidence bundle per remark:
   transcript slice + up to 3 frames + OCR + wall-clock range.
4. `extract_frame(job_id, at_ms, crop=...)` — exact instant, native
   resolution, when keyframes miss the moment.
5. `list_jobs()` — recordings processed earlier remain queryable.

Timestamps: `t_ms` is video-relative; `t_wall` is real wall-clock time when
the recording start is known — use it to correlate remarks with logs
(±30 s window). Audio-only files (.m4a/.mp3/…) have transcripts but no
frames; frame tools erroring on them is expected.

Full docs: https://github.com/korovin-aa97/talkthrough-mcp
"""
    return {"integrations/openclaw/clawhub/SKILL.md": content}


def build_integrations_index() -> dict[str, str]:
    content = f"""# Integrations

The talkthrough MCP server is engine-agnostic (stdio MCP). Server command:

```
{UVX_CMDLINE}
```

One folder per engine with the exact config to paste:

| Engine | Folder | Extras beyond the MCP config |
|---|---|---|
| Claude Code | [`claude-code/`](claude-code/) | full plugin: 5 slash commands, triage agent, skill |
| Claude Desktop | [`claude-desktop/`](claude-desktop/) | one-click `.mcpb` extension (draft) |
| OpenAI Codex CLI | [`codex/`](codex/) | `$talkthrough` skill via `.agents/skills/` |
| OpenClaw | [`openclaw/`](openclaw/) | ClawHub-ready skill wrapper |
| Gemini CLI | [`gemini-cli/`](gemini-cli/) | — |
| Cursor | [`cursor/`](cursor/) | — |
| Cline / Roo Code | [`cline/`](cline/) | agent self-install via `llms-install.md` |
| OpenCode | [`opencode/`](opencode/) | — |
| Goose | [`goose/`](goose/) | — |
| GitHub Copilot CLI | [`copilot-cli/`](copilot-cli/) | — |
| Windsurf | [`windsurf/`](windsurf/) | — |
| Zed | [`zed/`](zed/) | — |

Anything else that speaks MCP over stdio works with the same command. The
cross-engine [Agent Skill](https://agentskills.io) lives at
[`.agents/skills/talkthrough/`](../.agents/skills/talkthrough/) (Claude Code,
Codex, Cursor, Copilot, Gemini CLI, Goose and others read this format).

Config snippets are generated by `scripts/gen_integrations.py` from one
source of truth — do not hand-edit them. Snippet shapes verified against
engine docs 2026-07; each engine README links the authoritative docs.
"""
    return {"integrations/README.md": content}


def build_artifacts() -> dict[str, str]:
    artifacts: dict[str, str] = {}
    for builder in (
        build_claude_commands,
        build_example_prompts,
        build_skill_mirrors,
        build_agent_mirrors,
        build_mcp_configs,
        build_engine_docs,
        build_plugin_manifests,
        build_registry_manifest,
        build_clawhub_skill,
        build_integrations_index,
    ):
        artifacts.update(builder())
    return artifacts


def main() -> None:
    for rel_path, content in sorted(build_artifacts().items()):
        path = REPO / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(rel_path)
    readme = REPO / "README.md"
    readme.write_text(spliced_readme(readme.read_text(encoding="utf-8")), encoding="utf-8")
    print("README.md (install region)")


if __name__ == "__main__":
    main()
